### ISSUE TITLE
Bridge Auto Discovery doesn't work

### ISSUE THREAD

**Issue by hstamas** [mvdwetering/service.huecontrol#4]
When trying to detect the bridge nothing is found. Any chance of a fix or a manual method of inputing the bridge IP and username?

**Comment by mvdwetering** [comment]
It has been a while, but if I recall correctly in Kodi you cannot immediately use the IP and username. You must save the changes first before being able to access those settings. This means that things like saving presets won't work until you closed and reopened the settings window. 

This was the main reason I made the Autosearch and the fact that it just works.
Also the autosearch will pickup the bridge automatically up IP address changes if they happen.

So I would prefer to see if we can diagnose the issue and have a proper fix.
I  will try to make an update this weekend that can generate debug information to help diagnose the issue.
Until then, could you provoide me with some additional information:
 * Which Kodi version are you running?
 * Which Operating System are you using for Kodi?
 * And can you open the following URL on a PC that is in the same network as your hue bridge and tell me if your bridge is returned (or just post the output here). This is another way to discover a bridge which I have not implemented, but should not be really hard to do. http://www.meethue.com/api/nupnp

**Comment by hstamas** [comment]
That would be great if you could figure out the issue as your plugin has some nice features I would love to be able to use.

Answers to your questions:
Using Jarvis Beta v16 running on Windows 10 PC. I have also tried this on a Mac running Yosemite 10.10 with the same results.
Clicking on the bridge URL you posted does give me a positive return with the correct IP for my bridge.

**Comment by mvdwetering** [comment]
I have updated the addon with an additional method for finding bridges which should solve your issue (both methods are automatically used). Please try the new version. 
If you still have issues please enable Debuglogging in Kodi and search for bridges. Then send me the log file and I will see what is going wrong.

**Comment by hstamas** [comment]
Works perfectly. Thank you!

**Comment by mvdwetering** [comment]
Cool
