### ISSUE TITLE
Extend minimum length

### ISSUE THREAD

**Issue by hstamas** [mvdwetering/service.huecontrol#8]
@mvdwetering is there any way you could easily exert the minimum video length past 60 minutes? I only need the lights to turn off when minute series are activating the plugin and it’s quite inconvenient. Really hoping you could do this real quick as I’ve gotten your plugin working well again and don’t want to have to disable it.  I would think 90 minutes as a max would work for most situations?

**Comment by mvdwetering** [comment]
I have extend it to 90 minutes (its only a number), but I cannot make a release right now.
However I am a not sure how you intend to use it as I don't know what "minute series" are. The setting makes sure that the plugin _only_ acts when the movie is longer than min_video_lenghth.

**Comment by hstamas** [comment]
Thats excellent @mvdwetering. Thanks a lot. 

What I was incoherently trying to say above was that at the maximum 60 minute threshold, longer TV series like Game of Thrones that sometimes run 65 minutes are making the lights to turn off. By extending the default maximum to 90 minutes, that gives us some wiggle room for shows like that. 

I did actually find a way to set a new number by editing the "settings.xml" file found in the user data folder but it doesn't seem to stick 100% of the time. For what ever reason its getting written back to the default on occasion so a hard wired fix would be most appreciated.

Looking forward to your new release as I am finding that your plunging is definitely the most stable option out there for controlling Hue lights.

Thanks again for all your efforts!

**Comment by hstamas** [comment]
@mvdwetering any chance you can do a release with the above fix included?

**Comment by mvdwetering** [comment]
Sorry, I totally forgot about this.
I created a release and put it up as pre-release. Could you try that and report back if it works?
I am actually not using the addon myself anymore so I can't really test it, but since the change is small it should work.
If it work then I can mark the release as final.

**Comment by hstamas** [comment]
Works great. Thank you!

 I’m really surprised there isn’t more demand for plugins like yours. I really appreciate you updating this for what seems to be just for me!!

Would it be a lot of effort on your part to add the ability to tell the plugin to ignore live tv streams? I know add-ons like Trakt can do that. Issue is, if I use a PVR client within Kodi, since it’s a live stream, your plugin is detecting it as a very long video and activating.

**Comment by mvdwetering** [comment]
Adding ignoring of livestreams is not something trivial to do and since I am personally not using this addon anymore I won't be working on this. Sorry.

**Comment by mvdwetering** [comment]
BTW I consider this issue closed I submitted another ticker for the livestream request but that is only a reminder in case someone picks up development.
